// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS-q3yLqiCyNDXKRfTuCe4f4MWLQ4dAr0',
    appId: '1:842018643692:web:2f8af68c1b3e206cdecfc9',
    messagingSenderId: '842018643692',
    projectId: 'authtutorial-5753a',
    authDomain: 'authtutorial-5753a.firebaseapp.com',
    storageBucket: 'authtutorial-5753a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgjsTQwaFdzbW1ILDmy1jnvGH8vw68vV4',
    appId: '1:842018643692:android:b9e87798ebef6818decfc9',
    messagingSenderId: '842018643692',
    projectId: 'authtutorial-5753a',
    storageBucket: 'authtutorial-5753a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHVRL-LTqwKN-VXO-UIltM8eJQTaMNmc8',
    appId: '1:842018643692:ios:e4251e1cd9854c86decfc9',
    messagingSenderId: '842018643692',
    projectId: 'authtutorial-5753a',
    storageBucket: 'authtutorial-5753a.appspot.com',
    androidClientId: '842018643692-b69mjsv98kndq45sfq23stjrpea9h2gt.apps.googleusercontent.com',
    iosClientId: '842018643692-suq9mk0vjepks1dcl74smcu6bindiiji.apps.googleusercontent.com',
    iosBundleId: 'com.example.registerGoogle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHVRL-LTqwKN-VXO-UIltM8eJQTaMNmc8',
    appId: '1:842018643692:ios:e4251e1cd9854c86decfc9',
    messagingSenderId: '842018643692',
    projectId: 'authtutorial-5753a',
    storageBucket: 'authtutorial-5753a.appspot.com',
    androidClientId: '842018643692-b69mjsv98kndq45sfq23stjrpea9h2gt.apps.googleusercontent.com',
    iosClientId: '842018643692-suq9mk0vjepks1dcl74smcu6bindiiji.apps.googleusercontent.com',
    iosBundleId: 'com.example.registerGoogle',
  );
}
